// Code generated by hertz generator.

package v1

import (
	"context"
	"errors"
	"fmt"
	"log"

	"video-platform/biz/dal"
	"video-platform/biz/dal/model"
	v1 "video-platform/biz/model/api/video/v1"
	"video-platform/biz/service"
	"video-platform/pkg/response"
	"video-platform/pkg/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// 点赞操作类型常量（基于 Proto 枚举定义）
const (
	ActionTypeLike   = int32(v1.LikeActionType_LIKE_ACTION_TYPE_ADD)    // 1: 点赞
	ActionTypeUnlike = int32(v1.LikeActionType_LIKE_ACTION_TYPE_CANCEL) // 2: 取消点赞
)

// VideoLikeAction 点赞/取消点赞视频
// @router /api/v1/interaction/like [POST]
func VideoLikeAction(ctx context.Context, c *app.RequestContext) {
	var req v1.VideoLikeActionRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.VideoLikeActionResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 获取当前登录用户（中间件已验证）
	userID := c.GetUint("user_id")

	// 校验 video_id
	if req.VideoId == "" {
		c.JSON(consts.StatusBadRequest, &v1.VideoLikeActionResponse{
			Base: response.ParamError("video_id 不能为空"),
		})
		return
	}
	videoID, err := util.ParseUint(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.VideoLikeActionResponse{
			Base: response.ParamError("video_id 格式错误"),
		})
		return
	}

	// 校验 action_type
	actionType := req.ActionType
	if actionType != ActionTypeLike && actionType != ActionTypeUnlike {
		c.JSON(consts.StatusBadRequest, &v1.VideoLikeActionResponse{
			Base: response.ParamError("action_type 必须为 1（点赞）或 2（取消点赞）"),
		})
		return
	}

	svc := service.NewInteractionService(dal.GetStore())
	likeAction := service.LikeActionAdd
	if actionType == ActionTypeUnlike {
		likeAction = service.LikeActionCancel
	}

	_, err = svc.LikeVideo(ctx, userID, videoID, likeAction)
	if err != nil {
		if errors.Is(err, service.ErrVideoNotFound) {
			c.JSON(consts.StatusNotFound, &v1.VideoLikeActionResponse{
				Base: response.NotFound("视频不存在"),
			})
			return
		}
		log.Printf("[互动模块][点赞操作] 操作失败 video_id=%d user_id=%d: %v", videoID, userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.VideoLikeActionResponse{
			Base: response.InternalError(),
		})
		return
	}

	msg := "点赞成功"
	if actionType == ActionTypeUnlike {
		msg = "取消点赞成功"
	}
	c.JSON(consts.StatusOK, &v1.VideoLikeActionResponse{
		Base: response.Success(msg),
	})
}

// ListLikedVideos 获取用户点赞的视频列表
// @router /api/v1/interaction/like/list [GET]
func ListLikedVideos(ctx context.Context, c *app.RequestContext) {
	var req v1.ListLikedVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListLikedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 校验 user_id
	if req.UserId == "" {
		c.JSON(consts.StatusBadRequest, &v1.ListLikedVideosResponse{
			Base: response.ParamError("user_id 不能为空"),
		})
		return
	}
	userID, err := util.ParseUint(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListLikedVideosResponse{
			Base: response.ParamError("user_id 格式错误"),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)

	svc := service.NewInteractionService(dal.GetStore())
	videos, total, err := svc.ListLikedVideos(ctx, userID, offset, pageSize)
	if err != nil {
		log.Printf("[互动模块][点赞列表] 查询点赞列表失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.ListLikedVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	items := make([]*v1.Video, 0, len(videos))
	for i := range videos {
		items = append(items, modelToProtoVideo(&videos[i]))
	}

	c.JSON(consts.StatusOK, &v1.ListLikedVideosResponse{
		Base: response.Success(),
		Data: &v1.VideoListWithTotal{
			Items: items,
			Total: total,
		},
	})
}

// PublishComment 发布评论
// @router /api/v1/interaction/comment [POST]
func PublishComment(ctx context.Context, c *app.RequestContext) {
	var req v1.PublishCommentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.PublishCommentResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 获取当前登录用户（中间件已验证）
	userID := c.GetUint("user_id")

	// 校验 video_id
	if req.VideoId == "" {
		c.JSON(consts.StatusBadRequest, &v1.PublishCommentResponse{
			Base: response.ParamError("video_id 不能为空"),
		})
		return
	}
	videoID, err := util.ParseUint(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.PublishCommentResponse{
			Base: response.ParamError("video_id 格式错误"),
		})
		return
	}

	svc := service.NewInteractionService(dal.GetStore())
	err = svc.PublishComment(ctx, userID, videoID, req.Content)
	if err != nil {
		if errors.Is(err, service.ErrCommentEmpty) {
			c.JSON(consts.StatusBadRequest, &v1.PublishCommentResponse{
				Base: response.ParamError("评论内容不能为空"),
			})
			return
		}
		if errors.Is(err, service.ErrCommentTooLong) {
			c.JSON(consts.StatusBadRequest, &v1.PublishCommentResponse{
				Base: response.ParamError("评论内容不能超过 1000 字符"),
			})
			return
		}
		if errors.Is(err, service.ErrVideoNotFound) {
			c.JSON(consts.StatusNotFound, &v1.PublishCommentResponse{
				Base: response.NotFound("视频不存在"),
			})
			return
		}
		log.Printf("[互动模块][发布评论] 发布失败 video_id=%d user_id=%d: %v", videoID, userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.PublishCommentResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.PublishCommentResponse{
		Base: response.Success("评论成功"),
	})
}

// ListUserComments 获取用户发表的评论列表
// @router /api/v1/interaction/comment/list [GET]
func ListUserComments(ctx context.Context, c *app.RequestContext) {
	var req v1.ListUserCommentsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListUserCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 校验 user_id
	if req.UserId == "" {
		c.JSON(consts.StatusBadRequest, &v1.ListUserCommentsResponse{
			Base: response.ParamError("user_id 不能为空"),
		})
		return
	}
	userID, err := util.ParseUint(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListUserCommentsResponse{
			Base: response.ParamError("user_id 格式错误"),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)

	svc := service.NewInteractionService(dal.GetStore())
	comments, total, err := svc.ListUserComments(ctx, userID, offset, pageSize)
	if err != nil {
		log.Printf("[互动模块][评论列表] 查询评论列表失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.ListUserCommentsResponse{
			Base: response.InternalError(),
		})
		return
	}

	items := make([]*v1.Comment, 0, len(comments))
	for i := range comments {
		items = append(items, modelToProtoComment(&comments[i]))
	}

	c.JSON(consts.StatusOK, &v1.ListUserCommentsResponse{
		Base: response.Success(),
		Data: &v1.CommentListWithTotal{
			Items: items,
			Total: total,
		},
	})
}

// DeleteComment 删除评论
// @router /api/v1/interaction/comment/delete [POST]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var req v1.DeleteCommentRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.DeleteCommentResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 获取当前登录用户（中间件已验证）
	userID := c.GetUint("user_id")

	// 校验 comment_id
	if req.CommentId == "" {
		c.JSON(consts.StatusBadRequest, &v1.DeleteCommentResponse{
			Base: response.ParamError("comment_id 不能为空"),
		})
		return
	}
	commentID, err := util.ParseUint(req.CommentId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.DeleteCommentResponse{
			Base: response.ParamError("comment_id 格式错误"),
		})
		return
	}

	svc := service.NewInteractionService(dal.GetStore())
	err = svc.DeleteComment(ctx, userID, commentID)
	if err != nil {
		if errors.Is(err, service.ErrCommentNotFound) {
			c.JSON(consts.StatusNotFound, &v1.DeleteCommentResponse{
				Base: response.NotFound("评论不存在"),
			})
			return
		}
		if errors.Is(err, service.ErrNoPermission) {
			c.JSON(consts.StatusForbidden, &v1.DeleteCommentResponse{
				Base: response.Forbidden("无权删除他人评论"),
			})
			return
		}
		log.Printf("[互动模块][删除评论] 删除失败 comment_id=%d user_id=%d: %v", commentID, userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.DeleteCommentResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.DeleteCommentResponse{
		Base: response.Success("删除成功"),
	})
}

// modelToProtoComment 将数据库模型转换为 proto 格式
func modelToProtoComment(c *model.Comment) *v1.Comment {
	if c == nil {
		return nil
	}
	out := &v1.Comment{
		Id:         fmt.Sprintf("%d", c.ID),
		UserId:     fmt.Sprintf("%d", c.UserID),
		VideoId:    fmt.Sprintf("%d", c.VideoID),
		LikeCount:  c.LikeCount,
		ChildCount: c.ChildCount,
		Content:    c.Content,
		CreatedAt:  c.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:  c.UpdatedAt.Format("2006-01-02 15:04:05"),
	}
	if c.ParentID != nil {
		out.ParentId = fmt.Sprintf("%d", *c.ParentID)
	}
	if c.DeletedAt.Valid {
		out.DeletedAt = c.DeletedAt.Time.Format("2006-01-02 15:04:05")
	}
	return out
}
