// Code generated by hertz generator.

package v1

import (
	"context"
	"errors"
	"fmt"
	"log"

	"video-platform/biz/dal"
	"video-platform/biz/dal/model"
	v1 "video-platform/biz/model/api/video/v1"
	"video-platform/biz/service"
	"video-platform/pkg/response"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register 用户注册
// @router /api/v1/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var req v1.RegisterRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.RegisterResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	svc := service.NewUserService(dal.GetStore())
	_, err := svc.Register(ctx, req.Username, req.Password)
	if err != nil {
		if errors.Is(err, service.ErrUserExists) {
			c.JSON(consts.StatusOK, &v1.RegisterResponse{
				Base: response.Error(response.CodeUserExists),
			})
			return
		}
		log.Printf("[用户模块][注册] 注册失败 username=%s: %v", req.Username, err)
		c.JSON(consts.StatusInternalServerError, &v1.RegisterResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.RegisterResponse{
		Base: response.Success("注册成功"),
	})
}

// Login 用户登录
// @router /api/v1/user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var req v1.LoginRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.LoginResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	svc := service.NewUserService(dal.GetStore())
	result, err := svc.Login(ctx, req.Username, req.Password)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusOK, &v1.LoginResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		if errors.Is(err, service.ErrPasswordWrong) {
			c.JSON(consts.StatusOK, &v1.LoginResponse{
				Base: response.Error(response.CodePasswordWrong),
			})
			return
		}
		log.Printf("[用户模块][登录] 登录失败 username=%s: %v", req.Username, err)
		c.JSON(consts.StatusInternalServerError, &v1.LoginResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.LoginResponse{
		Base:         response.Success("登录成功"),
		Data:         modelToProtoUser(result.User),
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// RefreshToken 刷新令牌
// @router /api/v1/user/refresh [POST]
func RefreshToken(ctx context.Context, c *app.RequestContext) {
	var req v1.RefreshTokenRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.RefreshTokenResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if req.RefreshToken == "" {
		c.JSON(consts.StatusBadRequest, &v1.RefreshTokenResponse{
			Base: response.ParamError("refresh_token 不能为空"),
		})
		return
	}

	svc := service.NewUserService(dal.GetStore())
	result, err := svc.RefreshToken(ctx, req.RefreshToken)
	if err != nil {
		if errors.Is(err, service.ErrTokenExpired) {
			c.JSON(consts.StatusOK, &v1.RefreshTokenResponse{
				Base: response.Error(response.CodeTokenExpired),
			})
			return
		}
		c.JSON(consts.StatusOK, &v1.RefreshTokenResponse{
			Base: response.Error(response.CodeTokenInvalid),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.RefreshTokenResponse{
		Base:         response.Success("刷新成功"),
		AccessToken:  result.AccessToken,
		RefreshToken: result.RefreshToken,
	})
}

// GetUserInfo 获取用户信息
// @router /api/v1/user/info [GET]
func GetUserInfo(ctx context.Context, c *app.RequestContext) {
	var req v1.GetUserInfoRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.GetUserInfoResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if req.UserId == "" {
		c.JSON(consts.StatusBadRequest, &v1.GetUserInfoResponse{
			Base: response.ParamError("user_id 不能为空"),
		})
		return
	}

	// 将 user_id 转换为 uint
	var userID uint
	if _, err := fmt.Sscanf(req.UserId, "%d", &userID); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.GetUserInfoResponse{
			Base: response.ParamError("user_id 格式错误"),
		})
		return
	}

	svc := service.NewUserService(dal.GetStore())
	user, err := svc.GetUserByID(ctx, userID)
	if err != nil {
		if errors.Is(err, service.ErrUserNotFound) {
			c.JSON(consts.StatusOK, &v1.GetUserInfoResponse{
				Base: response.Error(response.CodeUserNotFound),
			})
			return
		}
		log.Printf("[用户模块][获取用户信息] 查询用户失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.GetUserInfoResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.GetUserInfoResponse{
		Base: response.Success(),
		Data: modelToProtoUser(user),
	})
}

// UploadAvatar 上传用户头像
// @router /api/v1/user/avatar [POST]
func UploadAvatar(ctx context.Context, c *app.RequestContext) {
	// 获取当前用户（中间件已验证）
	userID := c.GetUint("user_id")

	// 获取上传的文件
	fileHeader, err := c.FormFile("avatar")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.UploadAvatarResponse{
			Base: response.ParamError("请上传头像文件"),
		})
		return
	}

	// 生成文件名和保存路径
	filename := fmt.Sprintf("avatar_%d_%s", userID, fileHeader.Filename)
	savePath := fmt.Sprintf("storage/avatars/%s", filename)

	// 保存文件
	if err := c.SaveUploadedFile(fileHeader, savePath); err != nil {
		log.Printf("[用户模块][上传头像] 保存头像文件失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.UploadAvatarResponse{
			Base: response.InternalError(),
		})
		return
	}

	// 更新用户头像 URL
	avatarURL := fmt.Sprintf("/storage/avatars/%s", filename)
	svc := service.NewUserService(dal.GetStore())
	user, err := svc.UpdateAvatar(ctx, userID, avatarURL)
	if err != nil {
		log.Printf("[用户模块][上传头像] 更新头像失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.UploadAvatarResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.UploadAvatarResponse{
		Base: response.Success("头像上传成功"),
		Data: modelToProtoUser(user),
	})
}

// modelToProtoUser 将数据库模型转换为 Protobuf 用户结构
func modelToProtoUser(user *model.User) *v1.User {
	if user == nil {
		return nil
	}

	protoUser := &v1.User{
		Id:        fmt.Sprintf("%d", user.ID),
		Username:  user.Username,
		AvatarUrl: user.AvatarURL,
		CreatedAt: user.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt: user.UpdatedAt.Format("2006-01-02 15:04:05"),
	}

	if user.DeletedAt.Valid {
		protoUser.DeletedAt = user.DeletedAt.Time.Format("2006-01-02 15:04:05")
	}

	return protoUser
}
