// Code generated by hertz generator.

package v1

import (
	"context"
	"fmt"
	"log"
	"path/filepath"
	"strings"
	"time"

	"video-platform/biz/dal"
	"video-platform/biz/dal/model"
	v1 "video-platform/biz/model/api/video/v1"
	"video-platform/biz/service"
	"video-platform/pkg/response"
	"video-platform/pkg/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishVideo .
// @router /api/v1/video/publish [POST]
func PublishVideo(ctx context.Context, c *app.RequestContext) {
	var req v1.PublishVideoRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.PublishVideoResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	// 获取当前登录用户（中间件已验证）
	userID := c.GetUint("user_id")

	fileHeader, err := c.FormFile("video")
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.PublishVideoResponse{
			Base: response.ParamError("请上传视频文件,字段名为 video"),
		})
		return
	}

	title := strings.TrimSpace(req.Title)
	if title == "" {
		c.JSON(consts.StatusBadRequest, &v1.PublishVideoResponse{
			Base: response.ParamError("title 不能为空"),
		})
		return
	}

	// 生成文件名并保存到 storage/videos
	ext := filepath.Ext(fileHeader.Filename)
	if ext == "" {
		ext = ".mp4"
	}
	filename := fmt.Sprintf("video_%d_%d%s", userID, time.Now().UnixNano(), ext)
	savePath := filepath.Join("storage", "videos", filename)
	if err := c.SaveUploadedFile(fileHeader, savePath); err != nil {
		log.Printf("[视频模块][投稿] 保存视频文件失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.PublishVideoResponse{
			Base: response.InternalError(),
		})
		return
	}

	video := &model.Video{
		UserID:      userID,
		VideoURL:    fmt.Sprintf("/storage/videos/%s", filename),
		Title:       title,
		Description: strings.TrimSpace(req.Description),
	}

	svc := service.NewVideoService(dal.GetStore())
	if err := svc.CreateVideo(ctx, video); err != nil {
		log.Printf("[视频模块][投稿] 创建视频记录失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.PublishVideoResponse{
			Base: response.InternalError(),
		})
		return
	}

	c.JSON(consts.StatusOK, &v1.PublishVideoResponse{
		Base: response.Success("投稿成功"),
	})
}

// ListPublishedVideos .
// @router /api/v1/video/list [GET]
func ListPublishedVideos(ctx context.Context, c *app.RequestContext) {
	var req v1.ListPublishedVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListPublishedVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if req.UserId == "" {
		c.JSON(consts.StatusBadRequest, &v1.ListPublishedVideosResponse{
			Base: response.ParamError("user_id 不能为空"),
		})
		return
	}
	userID, err := util.ParseUint(req.UserId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListPublishedVideosResponse{
			Base: response.ParamError("user_id 格式错误"),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)

	svc := service.NewVideoService(dal.GetStore())
	videos, total, err := svc.ListVideosByUser(ctx, userID, offset, pageSize)
	if err != nil {
		log.Printf("[视频模块][发布列表] 查询发布列表失败 user_id=%d: %v", userID, err)
		c.JSON(consts.StatusInternalServerError, &v1.ListPublishedVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	items := make([]*v1.Video, 0, len(videos))
	for i := range videos {
		items = append(items, modelToProtoVideo(&videos[i]))
	}

	c.JSON(consts.StatusOK, &v1.ListPublishedVideosResponse{
		Base: response.Success(),
		Data: &v1.VideoListWithTotal{
			Items: items,
			Total: total,
		},
	})
}

// SearchVideos .
// @router /api/v1/video/search [GET]
func SearchVideos(ctx context.Context, c *app.RequestContext) {
	var req v1.SearchVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.SearchVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)
	sortBy := strings.TrimSpace(strings.ToLower(req.SortBy))
	sortByHot := sortBy == "hot"

	from, to := util.ParseUnixRange(req.FromDate, req.ToDate)

	svc := service.NewVideoService(dal.GetStore())
	videos, total, err := svc.SearchVideos(ctx, service.SearchVideosParams{
		Keywords:  strings.TrimSpace(req.Keywords),
		Username:  strings.TrimSpace(req.Username),
		FromDate:  from,
		ToDate:    to,
		SortByHot: sortByHot,
	}, offset, pageSize)
	if err != nil {
		log.Printf("[视频模块][搜索视频] 查询视频失败 keywords=%s username=%s: %v", req.Keywords, req.Username, err)
		c.JSON(consts.StatusInternalServerError, &v1.SearchVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	items := make([]*v1.Video, 0, len(videos))
	for i := range videos {
		items = append(items, modelToProtoVideo(&videos[i]))
	}

	c.JSON(consts.StatusOK, &v1.SearchVideosResponse{
		Base: response.Success(),
		Data: &v1.VideoListWithTotal{
			Items: items,
			Total: total,
		},
	})
}

// ListVideoComments .
// @router /api/v1/video/comments [GET]
func ListVideoComments(ctx context.Context, c *app.RequestContext) {
	var req v1.ListVideoCommentsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListVideoCommentsResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	if req.VideoId == "" {
		c.JSON(consts.StatusBadRequest, &v1.ListVideoCommentsResponse{
			Base: response.ParamError("video_id 不能为空"),
		})
		return
	}
	videoID, err := util.ParseUint(req.VideoId)
	if err != nil {
		c.JSON(consts.StatusBadRequest, &v1.ListVideoCommentsResponse{
			Base: response.ParamError("video_id 格式错误"),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)

	svc := service.NewVideoService(dal.GetStore())
	items, total, err := svc.ListVideoComments(ctx, videoID, offset, pageSize)
	if err != nil {
		log.Printf("[视频模块][视频评论列表] 查询评论列表失败 video_id=%d: %v", videoID, err)
		c.JSON(consts.StatusInternalServerError, &v1.ListVideoCommentsResponse{
			Base: response.InternalError(),
		})
		return
	}

	out := make([]*v1.VideoComment, 0, len(items))
	for _, it := range items {
		out = append(out, &v1.VideoComment{
			Id:        fmt.Sprintf("%d", it.ID),
			UserId:    fmt.Sprintf("%d", it.UserID),
			Username:  it.Username,
			AvatarUrl: it.AvatarURL,
			Content:   it.Content,
			LikeCount: it.LikeCount,
			CreatedAt: it.CreatedAt.Format("2006-01-02 15:04:05"),
		})
	}

	c.JSON(consts.StatusOK, &v1.ListVideoCommentsResponse{
		Base: response.Success(),
		Data: &v1.VideoCommentList{
			Items: out,
			Total: total,
		},
	})
}

// GetHotVideos .
// @router /api/v1/video/hot [GET]
func GetHotVideos(ctx context.Context, c *app.RequestContext) {
	var req v1.GetHotVideosRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, &v1.GetHotVideosResponse{
			Base: response.ParamError(err.Error()),
		})
		return
	}

	_, pageSize, offset := util.NormalizePage(req.PageNum, req.PageSize)

	svc := service.NewVideoService(dal.GetStore())
	videos, total, err := svc.GetHotVideos(ctx, offset, pageSize)
	if err != nil {
		log.Printf("[视频模块][热门排行榜] 查询热榜失败 page_num=%d page_size=%d: %v", req.PageNum, req.PageSize, err)
		c.JSON(consts.StatusInternalServerError, &v1.GetHotVideosResponse{
			Base: response.InternalError(),
		})
		return
	}

	items := make([]*v1.Video, 0, len(videos))
	for i := range videos {
		items = append(items, modelToProtoVideo(&videos[i]))
	}

	c.JSON(consts.StatusOK, &v1.GetHotVideosResponse{
		Base: response.Success(),
		Data: &v1.VideoListWithTotal{
			Items: items,
			Total: total,
		},
	})
}

func modelToProtoVideo(v *model.Video) *v1.Video {
	if v == nil {
		return nil
	}
	out := &v1.Video{
		Id:           fmt.Sprintf("%d", v.ID),
		UserId:       fmt.Sprintf("%d", v.UserID),
		VideoUrl:     v.VideoURL,
		CoverUrl:     v.CoverURL,
		Title:        v.Title,
		Description:  v.Description,
		VisitCount:   v.VisitCount,
		LikeCount:    v.LikeCount,
		CommentCount: v.CommentCount,
		CreatedAt:    v.CreatedAt.Format("2006-01-02 15:04:05"),
		UpdatedAt:    v.UpdatedAt.Format("2006-01-02 15:04:05"),
	}
	if v.DeletedAt.Valid {
		out.DeletedAt = v.DeletedAt.Time.Format("2006-01-02 15:04:05")
	}
	return out
}
