// Code generated by hertz generator.

package v1

import (
	"github.com/cloudwego/hertz/pkg/app"
	"video-platform/pkg/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadavatarMw() []app.HandlerFunc {
	// 上传头像需要认证
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _getuserinfoMw() []app.HandlerFunc {
	// 获取用户信息不需要认证
	return nil
}

func _loginMw() []app.HandlerFunc {
	// 登录不需要认证
	return nil
}

func _refreshtokenMw() []app.HandlerFunc {
	// 刷新令牌不需要认证
	return nil
}

func _registerMw() []app.HandlerFunc {
	// 注册不需要认证
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listvideocommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublishedvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishvideoMw() []app.HandlerFunc {
	// 投稿需要认证
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _searchvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _interactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishcommentMw() []app.HandlerFunc {
	// 发布评论需要认证
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _deletecommentMw() []app.HandlerFunc {
	// 删除评论需要认证
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _listusercommentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videolikeactionMw() []app.HandlerFunc {
	// 点赞操作需要认证
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}

func _listlikedvideosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _relationactionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfollowingsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listfriendsMw() []app.HandlerFunc {
	// your code...
	return nil
}
