CREATE DATABASE IF NOT EXISTS fanone_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS fanone_video CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS fanone_interaction CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
