// Code generated by hertz generator.

package main

import (
	"log"
	"os"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/hertz-contrib/cors"
	"github.com/joho/godotenv"
	"video-platform/biz/dal"
	"video-platform/pkg/logger"
	"video-platform/pkg/middleware"
	"video-platform/pkg/storage"
	"video-platform/swagger"
)

func main() {
	if err := logger.Init(); err != nil {
		log.Fatalf("初始化日志失败: %v", err)
	}
	defer func() {
		if err := logger.Sync(); err != nil {
			log.Printf("刷新日志缓冲失败: %v", err)
		}
	}()

	// 加载 .env 配置文件
	if err := godotenv.Load(); err != nil {
		log.Println("未找到 .env 文件，将使用系统环境变量")
	}

	// 初始化数据访问层（MySQL + Redis）
	dal.Init()

	port := os.Getenv("SERVER_PORT")
	if port == "" {
		port = "8888"
	}

	h := server.Default(server.WithHostPorts(":" + port))
	h.Use(middleware.RequestLogMiddleware())
	h.Use(cors.Default())

	register(h)

	// 挂载静态文件目录（头像、视频）
	storage.BindStatic(h)

	// 绑定 Swagger UI，访问 /swagger/index.html 查看接口文档
	swagger.BindSwagger(h)

	log.Printf("服务启动中，监听端口: %s", port)
	h.Spin()
}
