name: GolangCI-Lint

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/golangci-lint.yml"
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/golangci-lint.yml"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.1.6
          install-mode: goinstall
          args: --config=.golangci.yml
